# Generated by Django 3.0 on 2022-01-23 15:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220123_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='blog/default_blog_thumbnail.jpg', force_format=None, keep_meta=True, quality=75, size=[200, 250], upload_to='blog'),
        ),
    ]
